### ISSUE TITLE
Wrong element spaces while window resizing 

### ISSUE THREAD

**Issue by CrezZ** [osuru/edumeet-osu#1]
1) While width less 980px (RU) and 976px (EN) - wrong spaces
![image](https://user-images.githubusercontent.com/1792184/122178167-c7ac1e80-ce9f-11eb-9d40-c99230ca507e.png)

2) while size less 595px - loose all management buttons (mute, share, chat, files) and menu not containt this buttons
![image](https://user-images.githubusercontent.com/1792184/122178890-6fc1e780-cea0-11eb-81c0-12e6d733e23f.png)
![image](https://user-images.githubusercontent.com/1792184/122178938-7bada980-cea0-11eb-8c1f-0fa49047ce4d.png)

3) TWO menu button follow different menus (while width less 960px)! 
![image](https://user-images.githubusercontent.com/1792184/122179306-d5ae6f00-cea0-11eb-9be2-88fac89810e5.png)

4) Mobile view loose ANY menus and buttons
![image](https://user-images.githubusercontent.com/1792184/122179518-0bebee80-cea1-11eb-9136-ea11a1f91ae9.png)

5) Left panel does not fit tabs names
![image](https://user-images.githubusercontent.com/1792184/122180325-c24fd380-cea1-11eb-915f-745e6e408f98.png)

6) Left panel mobile view not cover width 100% 
![image](https://user-images.githubusercontent.com/1792184/122180558-f6c38f80-cea1-11eb-84b6-37b3b3423e56.png)

**Comment by CrezZ** [comment]
7) fully loose some buttons on resize
![image](https://user-images.githubusercontent.com/1792184/122182025-52424d00-cea3-11eb-8bbf-2373e2a5100a.png)

**Comment by m1trand1r** [comment]
bug 1 fixed

**Comment by m1trand1r** [comment]
all bugs fixed, continue work in mobile sector
